---
apiVersion: v1
kind: Service
metadata:
  name: sentry-webhooks
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: sentry-webhooks
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: sentry-webhooks
